version: "3"

services:
  postgresDatabase:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: TodoApp
      POSTGRES_PASSWORD: TodoPassword
      POSTGRES_DB: TodoApp
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgAdminPasswd!
    ports:
      - "8090:80"